#index:
#  path: /
#  controller: App\Controller\DefaultController::index

#compte:
#  path: /
#  controller: App\Controller\MonCompteController::modifier

#login:
#  path:       /login
#  controller: App\Controller\SecurityController::login
#  schemes:    [https]

modifier:
  path:       /compte/modifier/{id}
  controller: App\Controller\MoncompteController::modifier
